apiVersion: v1
kind: Pod
metadata:
  name: mem-stress
spec:
  restartPolicy: Never
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "1200M", "--vm-hang", "1"]
      resources:
        limits:
          memory: "1500Mi"
