- name: Create namespace
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/namespace.yaml"

- name: Apply ConfigMap
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/configmap.yaml"

- name: Apply Secret
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/secret.yaml"
